apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-bot
  template:
    metadata:
      labels:
        app: dispatcher-bot
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: dispatcher-bot
        image: eduardopuentec/florakube-bot:latest
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: florakube-secrets
              key: TELEGRAM_TOKEN
        - name: API_INVENTARIO_URL
          value: "http://api-inventario-service:8000"
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "10"]